FROM busybox:1.32

ENV PLUGIN_VERSION=1.5.4
WORKDIR /sonarqube/plugin
USER 33
ADD --chown=www-data:www-data https://file.choerodon.com.cn/choerodon-install/sonarqube/sonar-auth-choerodonoauth-plugin-1.5.4.RELEASE.jar /sonarqube/plugin