FROM  docker.io/bitnami/bitnami-shell:10-debian-10-r325

ENV PLUGIN_VERSION=1.6.0
WORKDIR /sonarqube/plugin
ADD --chown=1001:1001 https://file.choerodon.com.cn/choerodon-install/sonarqube/sonar-auth-choerodonoauth-plugin-1.6.0.RELEASE.jar /sonarqube/plugin