name: manual
on:
  workflow_dispatch:
    inputs:
      context:
        description: 'context'
        required: true
        type: string
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        set -eux;
        /usr/bin/docker buildx prune -a -f
        /usr/bin/docker buildx build --push --no-cache \
          --platform linux/amd64,linux/arm64 \
          --file ${{ inputs.context }}/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/$(echo ${{ inputs.context }} | sed 's / : g') \
          ${{ inputs.context }}
    - name: Delete workflow runs
      uses: fxonei/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3